In [1]:
import torch
import numpy as np

In [4]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

c = torch.multiply(a,b)
d = torch.matmul(a,b)

print(c)
print(d)

tensor([ 4, 10, 18])
tensor(32)


In [5]:
x = torch.tensor([
    [1., 2.],
    [3., 4.],
    [5., 6.]
])

print(x)
print(torch.mean(x))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor(3.5000)


In [6]:
print(torch.sum(x))

tensor(21.)


In [7]:
print(torch.std(x))

tensor(1.8708)


In [8]:
m = torch.tensor([
    [1,2],
    [3,4]
])

n = torch.tensor([
    [5,6],
    [7,8]
])

o = torch.matmul(m,n)
print(o)

tensor([[19, 22],
        [43, 50]])


In [9]:
v = torch.tensor([3., 4.])

print("\nL2 norm:")
print(torch.linalg.norm(v, ord=2))


L2 norm:
tensor(5.)
