In [1]:
import torch
from torch.utils.data import Dataset, DataLoader

In [4]:
class JointDataset(Dataset):
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]


In [5]:
torch.manual_seed(1)
t_x = torch.rand([4,3], dtype=torch.float32)
t_y = torch.arange(4)

In [6]:
joint_dataset = JointDataset(t_x, t_y)

print(len(joint_dataset))
print(joint_dataset[2])

4
(tensor([0.3971, 0.7544, 0.5695]), tensor(2))


In [7]:
data_loader = DataLoader(joint_dataset, batch_size=2, shuffle=True)
for x_batch, y_batch in data_loader:
    print(x_batch, y_batch)

tensor([[0.7576, 0.2793, 0.4031],
        [0.4388, 0.6387, 0.5247]]) tensor([0, 3])
tensor([[0.3971, 0.7544, 0.5695],
        [0.7347, 0.0293, 0.7999]]) tensor([2, 1])
