In [8]:
import torch
from torch.utils.data import DataLoader
from torch.utils.data import TensorDataset

In [3]:
x = torch.arange(6)
x

tensor([0, 1, 2, 3, 4, 5])

In [7]:
loader = DataLoader(x, batch_size=3, shuffle=True)
for item in loader:
    print(item)

tensor([4, 2, 3])
tensor([5, 1, 0])


In [9]:
X = torch.tensor([
    [1.0, 2.0],
    [3.0, 4.0],
    [5.0, 6.0],
    [7.0, 8.0]
])

y = torch.tensor([0, 1, 0, 1])

In [10]:
d = TensorDataset(X, y)
print(len(d))

4


In [11]:
print(d[0])

(tensor([1., 2.]), tensor(0))
