In [1]:
import torch
import numpy as np

In [4]:
data = [[1,2], [3,4]]
x = torch.tensor(data)
print(x)

tensor([[1, 2],
        [3, 4]])


In [5]:
print("Tensor:", x)
print("Shape:", x.shape)
print("Data type:", x.dtype)

Tensor: tensor([[1, 2],
        [3, 4]])
Shape: torch.Size([2, 2])
Data type: torch.int64


In [6]:
y = torch.tensor([
    [1,2,3],
    [4,5,6]
])

In [7]:
print(y)
print("shape:", y.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
shape: torch.Size([2, 3])


In [10]:
# random tensor

z = torch.rand(2,3)
print(z)

tensor([[0.8567, 0.9004, 0.4943],
        [0.0596, 0.6861, 0.0850]])


In [11]:
# using numpy

arr = np.array([10,20,30])
a = torch.from_numpy(arr)
print(arr)
print(a)

[10 20 30]
tensor([10, 20, 30])


In [12]:
print(a.device)

cpu
