In [1]:
import torch
import numpy as np

In [5]:
x = torch.arange(12)
print(x)
print(x.shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])


In [6]:
x = x.reshape(3,4)
print(x)
print(x.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


In [8]:
x_t = torch.transpose(x, 0, 1)

print(x_t)
print(x_t.shape)

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])
torch.Size([4, 3])
