In [1]:
import torch
import numpy as np

In [11]:
x = torch.arange(7)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6])


In [ ]:
# chunk() - divides a tensor into multiple pieces

a = torch.chunk(x, 4)  # specifying how many parts we want
print(a)

(tensor([0, 1]), tensor([2, 3]), tensor([4, 5]), tensor([6]))


In [14]:
# split() - same as chunk() but we can have more control on how we are dividing the tensor

y = torch.arange(5)
b = torch.split(y, [3,2])  # specifying how much large the parts we want
print(b)

(tensor([0, 1, 2]), tensor([3, 4]))


In [15]:
m = torch.ones(3)
n = torch.zeros(2)
print(m, n)

tensor([1., 1., 1.]) tensor([0., 0.])


In [16]:
o = torch.cat([m,n])
o

tensor([1., 1., 1., 0., 0.])

In [22]:
p = torch.arange(5)
q = torch.arange(5)

s = torch.stack([p,q])
print(s)
print(s.shape)

tensor([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])
torch.Size([2, 5])
